name: Master

on:
  push:
    branches:
      - master
jobs:
  test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint/Test Server
      run: |
        cd server
        npm ci
        npm run eslint
        npm test
      env:
        CI: true
  test-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build/Test Web
      run: |
        cd web
        npm ci
        npm test
        npm run build
      env:
        CI: true
  docker-build:
    needs: [test-server,test-web]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker
      run: |
        docker build -t michaelkohler/health-dashboard:$GITHUB_SHA .
      env:
        CI: true
    - name: Publish Docker
      if: github.ref === 'master'
      run: |
        echo $DOCKER_PASSWORD | docker login --username michaelkohler --password-stdin
        docker push michaelkohler/health-dashboard:$GITHUB_SHA
      env:
        CI: true
